rvm:
 - 1.8.7
branches:
  only:
    - production
before_script:
  - "cp config/database.yml.example config/database.yml"
  - "cp config/monit.yml.example config/monit.yml"
  - mysql -e "CREATE DATABASE nuntium_test;"
  - mysql -e "CREATE USER 'nuntium'@'localhost';"
  - mysql -e "SET PASSWORD FOR 'nuntium'@'localhost' = PASSWORD('secret');"
  - mysql -u root -e "GRANT ALL ON nuntium_test.* TO 'nuntium'@'localhost';"
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
  - bundle exec rake test
services:
  - memcache
