nuntium_services:
  - cron
  - managed_processes
  - generic_worker:
      slow: 1
      fast: 1
  - scheduled_jobs_service

# The queues section describes the RabbitMQ Queues in which to monitor
# The key for each queue is it's unique name. e.g. ao_queue.1.smpp.3. You can get the names of the queues
# by running sudo rabbitmqctl list_queues -p vhost, where vhost is specified in config/amqp.yml

queues:
  ao_queue.1.smpp.1:            # Unique name of the queue e.g. ao_queue.1.smpp.3
    limit: 50                   # Maximum number of items in queue before considered overloaded
    notify:
      email:
        - "someone@example.com" # Email address to notify when this queue is overloaded
  ao_queue.1.smpp.2:
    limit: 25
  application_queue.1:
    limit: 10
